server:
  port: 16001
spring:
  application:
    name: lbj-springboot

# 配置日志级别
logging:
  level:
    #    root: info
    root: info
  pattern:
    file: ./data/log/${spring.application.name}.log




