server:
  port: 18080
spring:
  application:
    name: lbj-com.lbj.saas-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: lbj-com.lbj.saas-provider
          uri: lb://lbj-com.lbj.saas-provider
          predicates:
            - Path=/provider/**
        - id: lbj-com.lbj.saas-consumer
          uri: lb://lbj-com.lbj.saas-consumer
          predicates:
            - Path=/consumer/**
        - id: lbj-com.lbj.saas-db
          uri: lb://lbj-com.lbj.saas-db
          predicates:
            - Path=/db/**

# 配置日志级别
logging:
  level:
    #    root: info
    root: info
  pattern:
    file: ./data/log/${spring.application.name}.log




