server:
  port: 18083
spring:
  application:
    name: lbj-com.lbj.saas-db
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/nacos?allowMultiQueries=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    username: root
    password: 123456


mybatis:
  #注意：一定要对应mapper映射xml文件的所在路径
  mapper-locations: classpath:mapper/*.xml
  # 注意：对应实体类的路径
  type-aliases-package: com.lbj.saas.model
  callSettersOnNulls: true
  configuration:
    #打印mybatis生成的sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #指定 MyBatis 如何自动映射 数据基表的列 NONE：不映射　PARTIAL:部分  FULL:全部
    auto-mapping-behavior: partial
    #使用驼峰命名法转换字段
    map-underscore-to-camel-case: true

# 配置日志级别
logging:
  level:
    #    root: info
    root: info
  pattern:
    file: ./data/log/${spring.application.name}.log




